# Generated by Django 2.2.13 on 2020-12-19 22:32

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190718_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='City or Town'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_of_nationality',
            field=django_countries.fields.CountryField(blank=True, default='US', max_length=2, verbose_name='Country of Nationality'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_of_residence',
            field=django_countries.fields.CountryField(blank=True, default='US', max_length=2, verbose_name='Country'),
        ),
    ]
