---
- name: Setup deploy user,install pakages and secure server 
  hosts: all 
  remote_user: root 
  roles:
      - common

- name: Install PostgreSQL and configure the database
  hosts: all
  remote_user: '{{ deploy_user }}'
  roles:
      - role: database 
  tags:
      - database
        
- name:  configure and provision nginx and letsencrypt ssl cert 
  hosts: all 
  remote_user: '{{ deploy_user }}' 
  roles:
      - role: nginx 
  tags:
      - nginx_le

- name: provision application code django, redis and celery etc. 
  hosts: all 
  remote_user:  '{{ deploy_user }}'
  roles:
      - role: web
  tags:
      - webapp 
